### ISSUE TITLE
Add a header to the Index page

### ISSUE THREAD

**Issue by nbkhope** [nbktechworld/full-stack-web-dev#12]
Right now the website doesn't have a header, usually what appears as a navigation bar at the top of a website.

- [ ] Use the `<header>` tag first thing under the `<body>`
- [ ] Make the background color be different from the color for the main content
- [ ] Include the `Site Title` in the header, linking it to the home page (the root, `/`. In this case you can use `index.html` for `href` attribute of the anchor tag).

**Comment by Pybite** [comment]
I would like to help with this

**Comment by nbkhope** [comment]
@Pybite some examples of header/ navigation bar you can base off

https://getbootstrap.com/docs/5.3/components/navbar/#color-schemes
