### ISSUE TITLE
Add footer to Sign Up page

### ISSUE THREAD

**Issue by nbkhope** [nbktechworld/full-stack-web-dev#2]
The signup.html page lacks a footer at the end of the website content. We need to add one.

- [ ] Use the `<footer>` tag right before the end of `</body>`
- [ ] Style the footer with a background color different from the main content one
- [ ] Add a copyright message with the © symbol and the year, like: `Copyright © 2024 Site Title`

**Comment by Pybite** [comment]
I would like to help with this
