### ISSUE TITLE
Add Contributing section to src/README

### ISSUE THREAD

**Issue by nbkhope** [nbktechworld/full-stack-web-dev#26]
We need to include a section in the src/README letting people know that they should first ask to work on an issue then wait to be assigned, before starting any work on it. The reason is many people could propose changes at the same time to the same issue without people knowing so there is time wasted doing the same thing twice plus we would have conflicting solutions to be dealt with separately.

Assignment should be first-comment first-serve basis. That is, if multiple people comment expressing willingness to help, take the earliest person who commented.

**Comment by martinsliz** [comment]
I'd like to work on this issue.

**Comment by martinsliz** [comment]
I've realized that there are two README.md files and you wanted the src/README updated - I am going to make the correction and add it to the src/README but do you want me to still leave it in the other one or delete it?

**Comment by nbkhope** [comment]
@martinsliz only src/README should be changed
