### ISSUE TITLE
Add a breadcrumb to the Sign Up page

### ISSUE THREAD

**Issue by nbkhope** [nbktechworld/full-stack-web-dev#27]
A breadcrumb is used for  navigation convenience.

Usually you see it at the top of the main content section, reading like:

`Home / Sign Up`

It shows you the steps the user took to reach the page. Usually, from home, it goes to Sign up.

The word home should be linked to the home/index page.

Reference: https://developer.mozilla.org/en-US/docs/Glossary/Breadcrumb

**Comment by karlasanc** [comment]
I can help with this one too
