### ISSUE TITLE
Add a heading before the video in index.html that says `Watch the Video`

### ISSUE THREAD

**Issue by nbkhope** [nbktechworld/full-stack-web-dev#32]

**Comment by AlecNesatColak** [comment]
I can help with this

**Comment by AlecNesatColak** [comment]
@nbkhope Is there also a way to make a feature branch in the Github UI? I was looking for this and ultimately couldn't find it so I opted for a forked PR.

**Comment by nbkhope** [comment]
@AlecNesatColak usually we work locally in our machine to develop the features, instead of relying solely on the GitHub website web interface.

Watch the lecture @ https://www.youtube.com/watch?v=bEpIwyNuJ-Q if you haven't. It goes over creating a feature branch locally, then pushing it to origin remote (which should be your fork/copy of the original repository) and making a pull request using the feature branch.

If you want to create branches on GitHub web interface, you can use the branch selector:

![image](https://github.com/nbktechworld/full-stack-web-dev/assets/13649002/a1836780-729e-4dc8-87f0-47b3454c8324)

Keep in mind you'd have to git fetch & checkout those remote branches locally if you want to do anything with them in your machine.

**Comment by nbkhope** [comment]
@AlecNesatColak some additional point:
- You don't need to create a new fork every time you work on a new issue. Just always use the same fork.
