### ISSUE TITLE
Add .gitignore file to root of the repository to prevent .DS_Store files from being committed

### ISSUE THREAD

**Issue by nbkhope** [nbktechworld/full-stack-web-dev#52]
Mac usually creates files called .DS_Store, but they aren't really relevant to the source code, so we should not be committing them to version control. To prevent accidental inclusion of those files, we usually define a `.gitignore` file in the root of the directory that tells git to ignore those files and not commit them.

Right now we have https://github.com/nbktechworld/full-stack-web-dev/blob/master/.DS_Store, which shouldn't really be committed.

- [x] Remove that .DS_Store file
- [x] Add `.gitignore` file with content `.DS_Store` in one line, so git ignores that filename going forward.

Reference: https://git-scm.com/docs/gitignore

**Comment by Pybite** [comment]
Hey this is relatively simple and easy to do. Can I work on this issue ?

**Comment by nbkhope** [comment]
@Pybite this issue isn't yet complete because the file still exists and wasnt removed. Let me know if you cant figure out how to remove .DS_Store.

.gitignore only tells git to ignore the file but it doesn't delete the file

**Comment by Pybite** [comment]
Just got it done 😅
