### ISSUE TITLE
Sign Up form biography field needs the label to be associated with textarea

### ISSUE THREAD

**Issue by nbkhope** [nbktechworld/full-stack-web-dev#6]
When you click the label for biography, it doesn't focus the textarea. We need to make it focus. To accomplish that, you can associate the label with the textarea.

- [ ] The textarea should have a unique `id` attribute.
- [ ] The value for textarea id should be used for the `for` attribute passed to the `<label>` tag.

**Comment by Pybite** [comment]
I would like to help with this
