### ISSUE TITLE
Move signup.html to a React component

### ISSUE THREAD

**Issue by nbkhope** [nbktechworld/full-stack-web-dev#76]
Now that we learned how to create React components and have a React application, let's move the sign up page to a React component.

- [ ] Create the file `web-client/pages/sign-up.js`
- [ ] Move the content between the open/close `<body>` tags there
- [ ] See if anything under `<head>` is relevant. Check `web-client/public/index.html` to see if there is already any global stuff there.
- [ ] Specific CSS files can be imported using `import './path/to/some.css`

Make a draft pull request early and comment asking for clarification if you need help.

**Comment by Pybite** [comment]
I would like to help with this
