### ISSUE TITLE
Create a backend endpoint to sign up a user

### ISSUE THREAD

**Issue by nbkhope** [nbktechworld/full-stack-web-dev#81]
Create the endpoint:
```
POST /users
```

That will take sign up form information. Use `req.body` to access the submitted form values.

Partial example of req.body:
```
{
  "email": "someone@mail.com",
  "birthdate": "2000-06-26",
  ...
}
```

Remember you can make endpoint with
```
app.post('/users', async function(req, res) {
  // write code here to insert into database
  // ...
  return res.send(createdUser);
});
```

**Comment by Pybite** [comment]
I would like to help with this

**Comment by nbkhope** [comment]
@Pybite good luck! Make a draft pull request and tag me if you need clarification or help
