### ISSUE TITLE
Submit sign up form in frontend using fetch (POST request) and use http://localhost:3001

### ISSUE THREAD

**Issue by nbkhope** [nbktechworld/full-stack-web-dev#82]
- [ ] Navigation blocked by https://github.com/nbktechworld/full-stack-web-dev/issues/83 Although you can this do this issue without navigating at the end working (it will just 404)

Now that we got a backend server, we should hook the frontend sign up form to that.

- [ ] Keep track of form values in the React state. For example:

```
const [formFields, setFormFields] = React.useState({
  // initial values:
  name: '',
  email: '',
  ...
});
```

Then associate value and onChange property of every user input control, like:
```
function onFieldChange(event) {
  setFormFields({
    ...formFields,
    [event.target.name]: event.target.value
  })
}
...
  <input ... value={formFields.email} onChange={onFieldChange}
  ...
  <input ... value={formFields.birthdate} onChange={onFieldChange}
```

After successful sign up, redirect the user to sign page. You can do it like this:

```
import { useNavigate } from 'react-router-dom';

...

  const navigate = useNavigate();
  ...
    fetch(...).then(() => navigate('/signin'))
  ...
```

**Comment by Pybite** [comment]
I would like to help with this
