### ISSUE TITLE
Make the website look nicer on small / mobile screen

### ISSUE THREAD

**Issue by nbkhope** [nbktechworld/full-stack-web-dev#9]
Usually a raw website appears zoomed out on mobile devices (small screen). To make it appear nicer and not zoomed out, we set the meta tag of name viewport, under the `<head>`, like so:

```
<meta name="viewport" content="width=device-width, initial-scale=1">
```

## Task list

- [ ] #10
- [ ] #11

**Comment by Pybite** [comment]
I would like to work on this
